/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "IData_Port.h"
#include "IData_Port_aliases.h"
#include "ISR_Capture.h"
#include "ISR_Reset.h"
#include "RESET.h"
#include "RESET_aliases.h"
#include "CS.h"
#include "CS_aliases.h"
#include "E.h"
#include "E_aliases.h"
#include "A0.h"
#include "A0_aliases.h"
#include "SPILCD.h"
#include "SPILCD_SPI_UART.h"
#include "SPILCD_PINS.h"
#include "SPILCD_SPI_UART_PVT.h"
#include "SPILCD_PVT.h"
#include "SPILCD_BOOT.h"
#include "LCD_CD.h"
#include "LCD_CD_aliases.h"
#include "Clock_1.h"
#include "LCD_RESET.h"
#include "LCD_RESET_aliases.h"
#include "SPILCD_sclk_m.h"
#include "SPILCD_sclk_m_aliases.h"
#include "SPILCD_mosi_m.h"
#include "SPILCD_mosi_m_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

